### ISSUE TITLE
bad cpu type

### ISSUE THREAD

**Issue by iwestlin** [JettChenT/wechat-exporter#6]
运行`sudo ./wechattweak-cli install`时提示
`sudo: unable to execute ./wechattweak-cli: Bad CPU type in executable`

我是intel芯片的mac...

**Comment by iwestlin** [comment]
看起来问题出在这里 https://github.com/JettChenT/WeChatTweak-CLI/blob/53e910066b2cea876dc6d1cadf2113a83daf7d89/Makefile#L6

作者的设备应该是m芯片的，不知道能不能构建一个intel的版本？我的mac没装swift，实在腾不出空间了😭

**Comment by JettChenT** [comment]
现在我用 Github action 同时在 arm 和 x86 架构下编译了。
https://github.com/JettChenT/WeChatTweak-CLI/releases/download/v1.3.1/wechattweak-cli-x64
这个 binary 下载一下试试？我本机是 arm 的，所以还没测试过 x86

**Comment by iwestlin** [comment]
我刚试了下，命令行执行 `sudo ./wechattweak-cli-x64 install` 提示安装成功了
<img width="560" alt="截屏2023-12-18 下午10 12 02" src="https://github.com/JettChenT/wechat-exporter/assets/6235509/720ef5fd-9f3b-49c5-9623-720e9dbbcdcf">
但是微信app无法打开（点击图标没反应
一开始我以为是微信版本问题，换成了3.8.4以后再试了几次还是不行，最后换成原版的 https://github.com/sunnyyoung/WeChatTweak-CLI 成功打开了😂

导出聊天记录的功能我已经通过别的办法实现了，所以目前没有迫切的使用需求了。。不过还是谢谢作者🙏
